/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Berkay
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public ArrayList<String> choose_set = new ArrayList<String>();

    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        adana = new javax.swing.JCheckBox();
        adiyaman = new javax.swing.JCheckBox();
        afyonkarahisar = new javax.swing.JCheckBox();
        agri = new javax.swing.JCheckBox();
        amasya = new javax.swing.JCheckBox();
        ankara = new javax.swing.JCheckBox();
        antalya = new javax.swing.JCheckBox();
        artvin = new javax.swing.JCheckBox();
        aydin = new javax.swing.JCheckBox();
        balikesir = new javax.swing.JCheckBox();
        bilecik = new javax.swing.JCheckBox();
        bingöl = new javax.swing.JCheckBox();
        bitlis = new javax.swing.JCheckBox();
        bolu = new javax.swing.JCheckBox();
        burdur = new javax.swing.JCheckBox();
        bursa = new javax.swing.JCheckBox();
        canakkale = new javax.swing.JCheckBox();
        cankiri = new javax.swing.JCheckBox();
        corum = new javax.swing.JCheckBox();
        denizli = new javax.swing.JCheckBox();
        diyarbakir = new javax.swing.JCheckBox();
        edirne = new javax.swing.JCheckBox();
        elazig = new javax.swing.JCheckBox();
        erzincan = new javax.swing.JCheckBox();
        erzurum = new javax.swing.JCheckBox();
        eskisehir = new javax.swing.JCheckBox();
        gaziantep = new javax.swing.JCheckBox();
        giresun = new javax.swing.JCheckBox();
        gumushane = new javax.swing.JCheckBox();
        hakkari = new javax.swing.JCheckBox();
        hatay = new javax.swing.JCheckBox();
        isparta = new javax.swing.JCheckBox();
        mersin = new javax.swing.JCheckBox();
        istanbul = new javax.swing.JCheckBox();
        izmir = new javax.swing.JCheckBox();
        kars = new javax.swing.JCheckBox();
        kastamonu = new javax.swing.JCheckBox();
        kayseri = new javax.swing.JCheckBox();
        kirklareli = new javax.swing.JCheckBox();
        kirsehir = new javax.swing.JCheckBox();
        konya = new javax.swing.JCheckBox();
        kutahya = new javax.swing.JCheckBox();
        malatya = new javax.swing.JCheckBox();
        manisa = new javax.swing.JCheckBox();
        kahramanmaras = new javax.swing.JCheckBox();
        mardin = new javax.swing.JCheckBox();
        mugla = new javax.swing.JCheckBox();
        mus = new javax.swing.JCheckBox();
        nevsehir = new javax.swing.JCheckBox();
        nigde = new javax.swing.JCheckBox();
        ordu = new javax.swing.JCheckBox();
        rize = new javax.swing.JCheckBox();
        sakarya = new javax.swing.JCheckBox();
        samsun = new javax.swing.JCheckBox();
        siirt = new javax.swing.JCheckBox();
        sinop = new javax.swing.JCheckBox();
        sivas = new javax.swing.JCheckBox();
        tekirdag = new javax.swing.JCheckBox();
        tokat = new javax.swing.JCheckBox();
        trabzon = new javax.swing.JCheckBox();
        tunceli = new javax.swing.JCheckBox();
        sanliurfa = new javax.swing.JCheckBox();
        usak = new javax.swing.JCheckBox();
        van = new javax.swing.JCheckBox();
        yozgat = new javax.swing.JCheckBox();
        zonguldak = new javax.swing.JCheckBox();
        aksaray = new javax.swing.JCheckBox();
        bayburt = new javax.swing.JCheckBox();
        karaman = new javax.swing.JCheckBox();
        kirikkale = new javax.swing.JCheckBox();
        batman = new javax.swing.JCheckBox();
        sirnak = new javax.swing.JCheckBox();
        bartin = new javax.swing.JCheckBox();
        ardahan = new javax.swing.JCheckBox();
        igdir = new javax.swing.JCheckBox();
        yalova = new javax.swing.JCheckBox();
        karabuk = new javax.swing.JCheckBox();
        kilis = new javax.swing.JCheckBox();
        osmaniye = new javax.swing.JCheckBox();
        duzce = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kargo Gidecek Şehirleri Seçtikten Sonra Tamam Butonuna Basınız");

        jButton1.setText("TAMAM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        adana.setText("Adana");

        adiyaman.setText("Adıyaman");

        afyonkarahisar.setText("Afyonkarahisar");

        agri.setText("Ağrı");

        amasya.setText("Amasya");

        ankara.setText("Ankara");

        antalya.setText("Antalya");

        artvin.setText("Artvin");

        aydin.setText("Aydın");

        balikesir.setText("Balıkesir");

        bilecik.setText("Bilecik");

        bingöl.setText("Bingöl");

        bitlis.setText("Bitlis");

        bolu.setText("Bolu");

        burdur.setText("Burdur");

        bursa.setText("Bursa");

        canakkale.setText("Çanakkale");

        cankiri.setText("Çankırı");

        corum.setText("Çorum");

        denizli.setText("Denizli");

        diyarbakir.setText("Diyarbakır");

        edirne.setText("Edirne");

        elazig.setText("Elazığ");

        erzincan.setText("Erzincan");

        erzurum.setText("Erzurum");

        eskisehir.setText("Eskisehir");

        gaziantep.setText("Gaziantep");

        giresun.setText("Giresun");

        gumushane.setText("Gümüşhane");

        hakkari.setText("Hakkari");

        hatay.setText("Hatay");

        isparta.setText("Isparta");

        mersin.setText("Mersin");

        istanbul.setText("İstanbul");

        izmir.setText("İzmir");

        kars.setText("Kars");

        kastamonu.setText("Kastamonu");

        kayseri.setText("Kayseri");

        kirklareli.setText("Kırklareli");

        kirsehir.setText("Kırşehir");

        konya.setText("Konya");

        kutahya.setText("Kütahya");

        malatya.setText("Malatya");

        manisa.setText("Manisa");

        kahramanmaras.setText("Kahramanmaraş");

        mardin.setText("Mardin");

        mugla.setText("Muğla");

        mus.setText("Muş");

        nevsehir.setText("Nevşehir");

        nigde.setText("Niğde");

        ordu.setText("Ordu");

        rize.setText("Rize");

        sakarya.setText("Sakarya");

        samsun.setText("Samsun");

        siirt.setText("Siirt");

        sinop.setText("Sinop");

        sivas.setText("Sivas");

        tekirdag.setText("Tekirdağ");

        tokat.setText("Tokat");

        trabzon.setText("Trabzon");

        tunceli.setText("Tunceli");

        sanliurfa.setText("Şanlıurfa");

        usak.setText("Uşak");

        van.setText("Van");

        yozgat.setText("Yozgat");

        zonguldak.setText("Zonguldak");

        aksaray.setText("Aksaray");

        bayburt.setText("Bayburt");

        karaman.setText("Karaman");

        kirikkale.setText("Kırıkkale");

        batman.setText("Batman");

        sirnak.setText("Şırnak");

        bartin.setText("Bartın");

        ardahan.setText("Ardahan");

        igdir.setText("Iğdır");

        yalova.setText("Yalova");

        karabuk.setText("Karabük");

        kilis.setText("Kilis");

        osmaniye.setText("Osmaniye");

        duzce.setText("Düzce");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adana)
                            .addComponent(adiyaman)
                            .addComponent(afyonkarahisar)
                            .addComponent(agri)
                            .addComponent(amasya)
                            .addComponent(ankara)
                            .addComponent(antalya)
                            .addComponent(artvin)
                            .addComponent(aydin)
                            .addComponent(balikesir))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bilecik)
                            .addComponent(bingöl)
                            .addComponent(bitlis)
                            .addComponent(bolu)
                            .addComponent(burdur)
                            .addComponent(bursa)
                            .addComponent(canakkale)
                            .addComponent(cankiri)
                            .addComponent(corum)
                            .addComponent(denizli))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diyarbakir)
                                    .addComponent(edirne)
                                    .addComponent(elazig)
                                    .addComponent(erzincan)
                                    .addComponent(erzurum)
                                    .addComponent(eskisehir)
                                    .addComponent(gaziantep)
                                    .addComponent(giresun)
                                    .addComponent(gumushane)
                                    .addComponent(hakkari))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hatay)
                                            .addComponent(isparta)
                                            .addComponent(mersin)
                                            .addComponent(istanbul)
                                            .addComponent(izmir)
                                            .addComponent(kars))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(konya)
                                            .addComponent(kutahya)
                                            .addComponent(malatya)
                                            .addComponent(manisa)
                                            .addComponent(kahramanmaras)
                                            .addComponent(mardin)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kastamonu)
                                            .addComponent(kayseri)
                                            .addComponent(kirklareli)
                                            .addComponent(kirsehir))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nigde)
                                            .addComponent(nevsehir)
                                            .addComponent(mus)
                                            .addComponent(mugla))))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ordu)
                                    .addComponent(rize)
                                    .addComponent(sakarya)
                                    .addComponent(samsun)
                                    .addComponent(siirt)
                                    .addComponent(sinop)
                                    .addComponent(sivas)
                                    .addComponent(tekirdag)
                                    .addComponent(tokat)
                                    .addComponent(trabzon))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tunceli)
                                    .addComponent(sanliurfa)
                                    .addComponent(usak)
                                    .addComponent(van)
                                    .addComponent(yozgat)
                                    .addComponent(zonguldak)
                                    .addComponent(aksaray)
                                    .addComponent(bayburt)
                                    .addComponent(karaman)
                                    .addComponent(kirikkale))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(duzce)
                                    .addComponent(osmaniye)
                                    .addComponent(kilis)
                                    .addComponent(karabuk)
                                    .addComponent(yalova)
                                    .addComponent(igdir)
                                    .addComponent(ardahan)
                                    .addComponent(bartin)
                                    .addComponent(sirnak)
                                    .addComponent(batman)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adana)
                    .addComponent(bilecik)
                    .addComponent(diyarbakir)
                    .addComponent(hatay)
                    .addComponent(konya)
                    .addComponent(ordu)
                    .addComponent(tunceli)
                    .addComponent(batman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adiyaman)
                    .addComponent(bingöl)
                    .addComponent(edirne)
                    .addComponent(isparta)
                    .addComponent(kutahya)
                    .addComponent(rize)
                    .addComponent(sanliurfa)
                    .addComponent(sirnak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afyonkarahisar)
                    .addComponent(bitlis)
                    .addComponent(elazig)
                    .addComponent(mersin)
                    .addComponent(malatya)
                    .addComponent(sakarya)
                    .addComponent(usak)
                    .addComponent(bartin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agri)
                    .addComponent(bolu)
                    .addComponent(erzincan)
                    .addComponent(istanbul)
                    .addComponent(manisa)
                    .addComponent(samsun)
                    .addComponent(van)
                    .addComponent(ardahan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amasya)
                    .addComponent(burdur)
                    .addComponent(erzurum)
                    .addComponent(izmir)
                    .addComponent(kahramanmaras)
                    .addComponent(siirt)
                    .addComponent(yozgat)
                    .addComponent(igdir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ankara)
                    .addComponent(bursa)
                    .addComponent(eskisehir)
                    .addComponent(kars)
                    .addComponent(mardin)
                    .addComponent(sinop)
                    .addComponent(zonguldak)
                    .addComponent(yalova))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(antalya)
                    .addComponent(canakkale)
                    .addComponent(gaziantep)
                    .addComponent(kastamonu)
                    .addComponent(mugla)
                    .addComponent(sivas)
                    .addComponent(aksaray)
                    .addComponent(karabuk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artvin)
                    .addComponent(cankiri)
                    .addComponent(giresun)
                    .addComponent(kayseri)
                    .addComponent(mus)
                    .addComponent(tekirdag)
                    .addComponent(bayburt)
                    .addComponent(kilis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aydin)
                    .addComponent(corum)
                    .addComponent(gumushane)
                    .addComponent(kirklareli)
                    .addComponent(nevsehir)
                    .addComponent(tokat)
                    .addComponent(karaman)
                    .addComponent(osmaniye))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balikesir)
                    .addComponent(denizli)
                    .addComponent(hakkari)
                    .addComponent(kirsehir)
                    .addComponent(nigde)
                    .addComponent(trabzon)
                    .addComponent(kirikkale)
                    .addComponent(duzce))
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (adana.isSelected()) {

            choose_set.add("Adana");

        } else {

            choose_set.remove("Adana");

        }
        if (adiyaman.isSelected()) {

            choose_set.add("Adıyaman");

        } else {

            choose_set.remove("Adıyaman");

        }
        if (afyonkarahisar.isSelected()) {

            choose_set.add("Afyonkarahisar");

        } else {

            choose_set.remove("Afyonkarahisar");

        }
        if (agri.isSelected()) {

            choose_set.add("Ağrı");

        } else {

            choose_set.remove("Ağrı");

        }
        if (amasya.isSelected()) {

            choose_set.add("Amasya");

        } else {

            choose_set.remove("Amasya");

        }
        if (ankara.isSelected()) {

            choose_set.add("Ankara");

        } else {

            choose_set.remove("Ankara");

        }
        if (antalya.isSelected()) {

            choose_set.add("Antalya");

        } else {

            choose_set.remove("Antalya");

        }
        if (ardahan.isSelected()) {

            choose_set.add("Ardahan");

        } else {

            choose_set.remove("Ardahan");

        }
        if (artvin.isSelected()) {

            choose_set.add("Artvin");

        } else {

            choose_set.remove("Artvin");

        }
        if (aydin.isSelected()) {

            choose_set.add("Aydın");

        } else {

            choose_set.remove("Aydın");

        }
        if (balikesir.isSelected()) {

            choose_set.add("Balıkesir");

        } else {

            choose_set.remove("Balıkesir");

        }
        if (bartin.isSelected()) {

            choose_set.add("Bartın");

        } else {

            choose_set.remove("Bartın");

        }
        if (batman.isSelected()) {

            choose_set.add("Batman");

        } else {

            choose_set.remove("Batman");

        }
        if (bayburt.isSelected()) {

            choose_set.add("Bayburt");

        } else {

            choose_set.remove("Bayburt");

        }
        if (bilecik.isSelected()) {

            choose_set.add("Bilecik");

        } else {

            choose_set.remove("Bilecik");

        }
        if (bingöl.isSelected()) {

            choose_set.add("Bingöl");

        } else {

            choose_set.remove("Bingöl");

        }
        if (bitlis.isSelected()) {

            choose_set.add("Bitlis");

        } else {

            choose_set.remove("Bitlis");

        }
        if (bolu.isSelected()) {

            choose_set.add("Bolu");

        } else {

            choose_set.remove("Bolu");

        }
        if (burdur.isSelected()) {

            choose_set.add("Burdur");

        } else {

            choose_set.remove("Burdur");

        }
        if (bursa.isSelected()) {

            choose_set.add("Bursa");

        } else {

            choose_set.remove("Bursa");

        }
        if (canakkale.isSelected()) {

            choose_set.add("Çanakkale");

        } else {

            choose_set.remove("Çanakkale");

        }
        if (cankiri.isSelected()) {

            choose_set.add("Çankırı");

        } else {

            choose_set.remove("Çankırı");

        }
        if (corum.isSelected()) {

            choose_set.add("Çorum");

        } else {

            choose_set.remove("Çorum");

        }
        if (denizli.isSelected()) {

            choose_set.add("Denizli");

        } else {

            choose_set.remove("Denizli");

        }
        if (diyarbakir.isSelected()) {

            choose_set.add("Diyarbakır");

        } else {

            choose_set.remove("Diyarbakır");

        }
        if (duzce.isSelected()) {

            choose_set.add("Düzce");

        } else {

            choose_set.remove("Düzce");

        }
        if (edirne.isSelected()) {

            choose_set.add("Edirne");

        } else {

            choose_set.remove("Edirne");

        }
        if (elazig.isSelected()) {

            choose_set.add("Elazığ");

        } else {

            choose_set.remove("Elazığ");

        }
        if (erzincan.isSelected()) {

            choose_set.add("Erzincan");

        } else {

            choose_set.remove("Erzincan");

        }
        if (erzurum.isSelected()) {

            choose_set.add("Erzurum");

        } else {

            choose_set.remove("Erzurum");

        }
        if (eskisehir.isSelected()) {

            choose_set.add("Eskişehir");

        } else {

            choose_set.remove("Eskişehir");

        }
        if (gaziantep.isSelected()) {

            choose_set.add("Gaziantep");

        } else {

            choose_set.remove("Gaziantep");

        }
        if (giresun.isSelected()) {

            choose_set.add("Giresun");

        } else {

            choose_set.remove("Giresun");

        }
        if (gumushane.isSelected()) {

            choose_set.add("Gümüşhane");

        } else {

            choose_set.remove("Gümüşhane");

        }
        if (hakkari.isSelected()) {

            choose_set.add("Hakkari");

        } else {

            choose_set.remove("Hakkari");

        }
        if (hatay.isSelected()) {

            choose_set.add("Hatay");

        } else {

            choose_set.remove("Hatay");

        }
        if (igdir.isSelected()) {

            choose_set.add("Iğdır");

        } else {

            choose_set.remove("Iğdır");

        }
        if (isparta.isSelected()) {

            choose_set.add("Isparta");

        } else {

            choose_set.remove("Isparta");

        }
        if (istanbul.isSelected()) {

            choose_set.add("İstanbul");

        } else {

            choose_set.remove("İstanbul");

        }
        if (izmir.isSelected()) {

            choose_set.add("İzmir");

        } else {

            choose_set.remove("İzmir");

        }
        if (kahramanmaras.isSelected()) {

            choose_set.add("Kahramanmaraş");

        } else {

            choose_set.remove("Kahramanmaraş");

        }
        if (karabuk.isSelected()) {

            choose_set.add("Karabük");

        } else {

            choose_set.remove("Karabük");

        }
        if (karaman.isSelected()) {

            choose_set.add("Karaman");

        } else {

            choose_set.remove("Karaman");

        }
        if (kars.isSelected()) {

            choose_set.add("Kars");

        } else {

            choose_set.remove("Kars");

        }
        if (kastamonu.isSelected()) {

            choose_set.add("Kastamonu");

        } else {

            choose_set.remove("Kastamonu");

        }
        if (kayseri.isSelected()) {

            choose_set.add("Kayseri");

        } else {

            choose_set.remove("Kayseri");

        }
        if (kilis.isSelected()) {

            choose_set.add("Kilis");

        } else {

            choose_set.remove("Kilis");

        }
        if (kirikkale.isSelected()) {

            choose_set.add("Kırıkkale");

        } else {

            choose_set.remove("Kırıkkale");

        }
        if (kirklareli.isSelected()) {

            choose_set.add("Kırklareli");

        } else {

            choose_set.remove("Kırklareli");

        }
        if (kirsehir.isSelected()) {

            choose_set.add("Kırşehir");

        } else {

            choose_set.remove("Kırşehir");

        }
        if (konya.isSelected()) {

            choose_set.add("Konya");

        } else {

            choose_set.remove("Konya");

        }
        if (kutahya.isSelected()) {

            choose_set.add("Kütahya");

        } else {

            choose_set.remove("Kütahya");

        }
        if (malatya.isSelected()) {

            choose_set.add("Malatya");

        } else {

            choose_set.remove("Malatya");

        }
        if (manisa.isSelected()) {

            choose_set.add("Manisa");

        } else {

            choose_set.remove("Manisa");

        }
        if (mardin.isSelected()) {

            choose_set.add("Mardin");

        } else {

            choose_set.remove("Mardin");

        }
        if (mersin.isSelected()) {

            choose_set.add("Mersin");

        } else {

            choose_set.remove("Mersin");

        }
        if (mugla.isSelected()) {

            choose_set.add("Muğla");

        } else {

            choose_set.remove("Muğla");

        }
        if (mus.isSelected()) {

            choose_set.add("Muş");

        } else {

            choose_set.remove("Muş");

        }
        if (nevsehir.isSelected()) {

            choose_set.add("Nevşehir");

        } else {

            choose_set.remove("Nevşehir");

        }
        if (nigde.isSelected()) {

            choose_set.add("Niğde");

        } else {

            choose_set.remove("Niğde");

        }
        if (ordu.isSelected()) {

            choose_set.add("Ordu");

        } else {

            choose_set.remove("Ordu");

        }
        if (osmaniye.isSelected()) {

            choose_set.add("Osmaniye");

        } else {

            choose_set.remove("Osmaniye");

        }
        if (rize.isSelected()) {

            choose_set.add("Rize");

        } else {

            choose_set.remove("Rize");

        }
        if (sakarya.isSelected()) {

            choose_set.add("Sakarya");

        } else {

            choose_set.remove("Sakarya");

        }
        if (samsun.isSelected()) {

            choose_set.add("Samsun");

        } else {

            choose_set.remove("Samsun");

        }
        if (sanliurfa.isSelected()) {

            choose_set.add("Şanlıurfa");

        } else {

            choose_set.remove("Şanlıurfa");

        }
        if (siirt.isSelected()) {

            choose_set.add("Siirt");

        } else {

            choose_set.remove("Siirt");

        }
        if (sinop.isSelected()) {

            choose_set.add("Sinop");

        } else {

            choose_set.remove("Sinop");

        }
        if (sirnak.isSelected()) {

            choose_set.add("Şırnak");

        } else {

            choose_set.remove("Şırnak");

        }
        if (sivas.isSelected()) {

            choose_set.add("Sivas");

        } else {

            choose_set.remove("Sivas");

        }
        if (tekirdag.isSelected()) {

            choose_set.add("Tekirdağ");

        } else {

            choose_set.remove("Tekirdağ");

        }
        if (tokat.isSelected()) {

            choose_set.add("Tokat");

        } else {

            choose_set.remove("Tokat");

        }
        if (trabzon.isSelected()) {

            choose_set.add("Trabzon");

        } else {

            choose_set.remove("Trabzon");

        }
        if (tunceli.isSelected()) {

            choose_set.add("Tunceli");

        } else {

            choose_set.remove("Tunceli");

        }
        if (usak.isSelected()) {

            choose_set.add("Uşak");

        } else {

            choose_set.remove("Uşak");

        }
        if (van.isSelected()) {

            choose_set.add("Van");

        } else {

            choose_set.remove("Van");

        }
        if (yalova.isSelected()) {

            choose_set.add("Yalova");

        } else {

            choose_set.remove("Yalova");

        }
        if (yozgat.isSelected()) {

            choose_set.add("Yozgat");

        } else {

            choose_set.remove("Yozgat");

        }
        if (zonguldak.isSelected()) {

            choose_set.add("Zonguldak");

        } else {

            choose_set.remove("Zonguldak");

        }

        setVisible(false);

        Node adana = new Node("Adana", 1);
        Node adiyaman = new Node("Adıyaman", 2);
        Node afyonkarahisar = new Node("Afyonkarahisar", 3);
        Node agri = new Node("Ağrı", 4);
        Node amasya = new Node("Amasya", 5);
        Node ankara = new Node("Ankara", 6);
        Node antalya = new Node("Antalya", 7);
        Node artvin = new Node("Artvin", 8);
        Node aydin = new Node("Aydın", 9);
        Node balikesir = new Node("Balıkesir", 10);
        Node bilecik = new Node("Bilecik", 11);
        Node bingöl = new Node("Bingöl", 12);
        Node bitlis = new Node("Bitlis", 13);
        Node bolu = new Node("Bolu", 14);
        Node burdur = new Node("Burdur", 15);
        Node bursa = new Node("Bursa", 16);
        Node canakkale = new Node("Çanakkale", 17);
        Node cankiri = new Node("Çankırı", 18);
        Node corum = new Node("Çorum", 19);
        Node denizli = new Node("Denizli", 20);
        Node diyarbakir = new Node("Diyarbakır", 21);
        Node edirne = new Node("Edirne", 22);
        Node elazig = new Node("Elazığ", 23);
        Node erzincan = new Node("Erzincan", 24);
        Node erzurum = new Node("Erzurum", 25);
        Node eskisehir = new Node("Eşkişehir", 26);
        Node gaziantep = new Node("Gaziantep", 27);
        Node giresun = new Node("Giresun", 28);
        Node gumushane = new Node("Gümüşhane", 29);
        Node hakkari = new Node("Hakkari", 30);
        Node hatay = new Node("Hatay", 31);
        Node isparta = new Node("Isparta", 32);
        Node mersin = new Node("Mersin", 33);
        Node istanbul = new Node("İstanbul", 34);
        Node izmir = new Node("İzmir", 35);
        Node kars = new Node("Kars", 36);
        Node kastamonu = new Node("Kastamonu", 37);
        Node kayseri = new Node("Kayseri", 38);
        Node kirklareli = new Node("Kırklareli", 39);
        Node kirsehir = new Node("Kırşehir", 40);
        Node kocaeli = new Node("Kocaeli", 41);
        Node konya = new Node("Konya", 42);
        Node kutahya = new Node("Kütahya", 43);
        Node malatya = new Node("Malatya", 44);
        Node manisa = new Node("Manisa", 45);
        Node kahramanmaras = new Node("Kahramanmaraş", 46);
        Node mardin = new Node("Mardin", 47);
        Node mugla = new Node("Muğla", 48);
        Node mus = new Node("Muş", 49);
        Node nevsehir = new Node("Nevşehir", 50);
        Node nigde = new Node("Niğde", 51);
        Node ordu = new Node("Ordu", 52);
        Node rize = new Node("Rize", 53);
        Node sakarya = new Node("Sakarya", 54);
        Node samsun = new Node("Samsun", 55);
        Node siirt = new Node("Siirt", 56);
        Node sinop = new Node("Sinop", 57);
        Node sivas = new Node("Sivas", 58);
        Node tekirdag = new Node("Tekirdağ", 59);
        Node tokat = new Node("Tokat", 60);
        Node trabzon = new Node("Trabzon", 61);
        Node tunceli = new Node("Tunceli", 62);
        Node sanliurfa = new Node("Şanlıurfa", 63);
        Node usak = new Node("Uşak", 64);
        Node van = new Node("Van", 65);
        Node yozgat = new Node("Yozgat", 66);
        Node zonguldak = new Node("Zonguldak", 67);
        Node aksaray = new Node("Aksaray", 68);
        Node bayburt = new Node("Bayburt", 69);
        Node karaman = new Node("Karaman", 70);
        Node kirikkale = new Node("Kırıkkale", 71);
        Node batman = new Node("Batman", 72);
        Node sirnak = new Node("Şırnak", 73);
        Node bartin = new Node("Bartın", 74);
        Node ardahan = new Node("Ardahan", 75);
        Node igdir = new Node("Iğdır", 76);
        Node yalova = new Node("Yalova", 77);
        Node karabuk = new Node("Karabük", 78);
        Node kilis = new Node("Kilis", 79);
        Node osmaniye = new Node("Osmaniye", 80);
        Node duzce = new Node("Düzce", 81);

        adana.addNeighbour(hatay);
        adana.addNeighbour(osmaniye);
        adana.addNeighbour(kahramanmaras);
        adana.addNeighbour(kayseri);
        adana.addNeighbour(nigde);
        adana.addNeighbour(mersin);
        adana.addDistance(191);
        adana.addDistance(87);
        adana.addDistance(192);
        adana.addDistance(335);
        adana.addDistance(207);
        adana.addDistance(69);

        adiyaman.addNeighbour(sanliurfa);
        adana.addNeighbour(diyarbakir);
        adana.addNeighbour(malatya);
        adana.addNeighbour(kahramanmaras);
        adana.addNeighbour(gaziantep);
        adiyaman.addDistance(112);
        adiyaman.addDistance(207);
        adiyaman.addDistance(187);
        adiyaman.addDistance(163);
        adiyaman.addDistance(150);

        afyonkarahisar.addNeighbour(isparta);
        afyonkarahisar.addNeighbour(konya);
        afyonkarahisar.addNeighbour(eskisehir);
        afyonkarahisar.addNeighbour(kutahya);
        afyonkarahisar.addNeighbour(usak);
        afyonkarahisar.addNeighbour(denizli);
        afyonkarahisar.addNeighbour(burdur);
        afyonkarahisar.addDistance(168);
        afyonkarahisar.addDistance(223);
        afyonkarahisar.addDistance(144);
        afyonkarahisar.addDistance(100);
        afyonkarahisar.addDistance(115);
        afyonkarahisar.addDistance(222);
        afyonkarahisar.addDistance(169);

        agri.addNeighbour(van);
        agri.addNeighbour(igdir);
        agri.addNeighbour(kars);
        agri.addNeighbour(erzurum);
        agri.addNeighbour(mus);
        agri.addNeighbour(bitlis);
        agri.addDistance(228);
        agri.addDistance(143);
        agri.addDistance(214);
        agri.addDistance(183);
        agri.addDistance(245);
        agri.addDistance(234);

        amasya.addNeighbour(yozgat);
        amasya.addNeighbour(tokat);
        amasya.addNeighbour(samsun);
        amasya.addNeighbour(corum);
        amasya.addDistance(200);
        amasya.addDistance(114);
        amasya.addDistance(131);
        amasya.addDistance(92);

        ankara.addNeighbour(konya);
        ankara.addNeighbour(aksaray);
        ankara.addNeighbour(kirsehir);
        ankara.addNeighbour(kirikkale);
        ankara.addNeighbour(cankiri);
        ankara.addNeighbour(bolu);
        ankara.addNeighbour(eskisehir);
        ankara.addDistance(258);
        ankara.addDistance(225);
        ankara.addDistance(184);
        ankara.addDistance(75);
        ankara.addDistance(130);
        ankara.addDistance(191);
        ankara.addDistance(233);

        antalya.addNeighbour(mersin);
        antalya.addNeighbour(karaman);
        antalya.addNeighbour(konya);
        antalya.addNeighbour(isparta);
        antalya.addNeighbour(burdur);
        antalya.addNeighbour(mugla);
        antalya.addDistance(466);
        antalya.addDistance(374);
        antalya.addDistance(322);
        antalya.addDistance(130);
        antalya.addDistance(122);
        antalya.addDistance(311);

        artvin.addNeighbour(rize);
        artvin.addNeighbour(erzurum);
        artvin.addNeighbour(ardahan);
        artvin.addDistance(161);
        artvin.addDistance(226);
        artvin.addDistance(116);

        aydin.addNeighbour(mugla);
        aydin.addNeighbour(denizli);
        aydin.addNeighbour(manisa);
        aydin.addNeighbour(izmir);
        aydin.addDistance(99);
        aydin.addDistance(126);
        aydin.addDistance(155);
        aydin.addDistance(126);

        balikesir.addNeighbour(izmir);
        balikesir.addNeighbour(manisa);
        balikesir.addNeighbour(kutahya);
        balikesir.addNeighbour(bursa);
        balikesir.addNeighbour(canakkale);
        balikesir.addDistance(176);
        balikesir.addDistance(141);
        balikesir.addDistance(228);
        balikesir.addDistance(151);
        balikesir.addDistance(198);

        bilecik.addNeighbour(kutahya);
        bilecik.addNeighbour(eskisehir);
        bilecik.addNeighbour(bolu);
        bilecik.addNeighbour(sakarya);
        bilecik.addNeighbour(bursa);
        bilecik.addDistance(112);
        bilecik.addDistance(83);
        bilecik.addDistance(213);
        bilecik.addDistance(99);
        bilecik.addDistance(94);

        bingöl.addNeighbour(diyarbakir);
        bingöl.addNeighbour(mus);
        bingöl.addNeighbour(erzurum);
        bingöl.addNeighbour(erzincan);
        bingöl.addNeighbour(tunceli);
        bingöl.addNeighbour(elazig);
        bingöl.addDistance(141);
        bingöl.addDistance(111);
        bingöl.addDistance(177);
        bingöl.addDistance(275);
        bingöl.addDistance(144);
        bingöl.addDistance(144);

        bitlis.addNeighbour(siirt);
        bitlis.addNeighbour(van);
        bitlis.addNeighbour(agri);
        bitlis.addNeighbour(mus);
        bitlis.addNeighbour(batman);
        bitlis.addDistance(96);
        bitlis.addDistance(161);
        bitlis.addDistance(234);
        bitlis.addDistance(83);
        bitlis.addDistance(135);

        bolu.addNeighbour(eskisehir);
        bolu.addNeighbour(ankara);
        bolu.addNeighbour(cankiri);
        bolu.addNeighbour(zonguldak);
        bolu.addNeighbour(duzce);
        bolu.addNeighbour(sakarya);
        bolu.addNeighbour(bilecik);
        bolu.addNeighbour(karabuk);
        bolu.addDistance(291);
        bolu.addDistance(191);
        bolu.addDistance(233);
        bolu.addDistance(157);
        bolu.addDistance(45);
        bolu.addDistance(114);
        bolu.addDistance(213);
        bolu.addDistance(134);

        burdur.addNeighbour(mugla);
        burdur.addNeighbour(antalya);
        burdur.addNeighbour(isparta);
        burdur.addNeighbour(afyonkarahisar);
        burdur.addNeighbour(denizli);
        burdur.addDistance(241);
        burdur.addDistance(122);
        burdur.addDistance(51);
        burdur.addDistance(169);
        burdur.addDistance(150);

        bursa.addNeighbour(balikesir);
        bursa.addNeighbour(kutahya);
        bursa.addNeighbour(bilecik);
        bursa.addNeighbour(sakarya);
        bursa.addNeighbour(kocaeli);
        bursa.addNeighbour(yalova);
        bursa.addDistance(151);
        bursa.addDistance(177);
        bursa.addDistance(94);
        bursa.addDistance(157);
        bursa.addDistance(132);
        bursa.addDistance(69);

        canakkale.addNeighbour(balikesir);
        canakkale.addNeighbour(tekirdag);
        canakkale.addNeighbour(edirne);
        canakkale.addDistance(198);
        canakkale.addDistance(187);
        canakkale.addDistance(216);

        cankiri.addNeighbour(ankara);
        cankiri.addNeighbour(kirikkale);
        cankiri.addNeighbour(corum);
        cankiri.addNeighbour(kastamonu);
        cankiri.addNeighbour(bolu);
        cankiri.addNeighbour(karabuk);
        cankiri.addDistance(130);
        cankiri.addDistance(104);
        cankiri.addDistance(156);
        cankiri.addDistance(106);
        cankiri.addDistance(233);
        cankiri.addDistance(193);

        corum.addNeighbour(yozgat);
        corum.addNeighbour(amasya);
        corum.addNeighbour(samsun);
        corum.addNeighbour(sinop);
        corum.addNeighbour(kastamonu);
        corum.addNeighbour(cankiri);
        corum.addNeighbour(kirikkale);
        corum.addDistance(108);
        corum.addDistance(92);
        corum.addDistance(172);
        corum.addDistance(266);
        corum.addDistance(197);
        corum.addDistance(156);
        corum.addDistance(166);

        denizli.addNeighbour(mugla);
        denizli.addNeighbour(burdur);
        denizli.addNeighbour(afyonkarahisar);
        denizli.addNeighbour(usak);
        denizli.addNeighbour(manisa);
        denizli.addNeighbour(aydin);
        denizli.addDistance(145);
        denizli.addDistance(150);
        denizli.addDistance(222);
        denizli.addDistance(150);
        denizli.addDistance(208);
        denizli.addDistance(126);

        diyarbakir.addNeighbour(sanliurfa);
        diyarbakir.addNeighbour(mardin);
        diyarbakir.addNeighbour(batman);
        diyarbakir.addNeighbour(mus);
        diyarbakir.addNeighbour(bingöl);
        diyarbakir.addNeighbour(elazig);
        diyarbakir.addNeighbour(malatya);
        diyarbakir.addNeighbour(adiyaman);
        diyarbakir.addDistance(176);
        diyarbakir.addDistance(96);
        diyarbakir.addDistance(100);
        diyarbakir.addDistance(252);
        diyarbakir.addDistance(141);
        diyarbakir.addDistance(153);
        diyarbakir.addDistance(249);
        diyarbakir.addDistance(207);

        edirne.addNeighbour(canakkale);
        edirne.addNeighbour(tekirdag);
        edirne.addNeighbour(kirklareli);
        edirne.addDistance(216);
        edirne.addDistance(140);
        edirne.addDistance(62);

        elazig.addNeighbour(diyarbakir);
        elazig.addNeighbour(bingöl);
        elazig.addNeighbour(tunceli);
        elazig.addNeighbour(erzincan);
        elazig.addNeighbour(malatya);
        elazig.addDistance(153);
        elazig.addDistance(144);
        elazig.addDistance(136);
        elazig.addDistance(267);
        elazig.addDistance(98);

        erzincan.addNeighbour(elazig);
        erzincan.addNeighbour(tunceli);
        erzincan.addNeighbour(bingöl);
        erzincan.addNeighbour(erzurum);
        erzincan.addNeighbour(bayburt);
        erzincan.addNeighbour(gumushane);
        erzincan.addNeighbour(giresun);
        erzincan.addNeighbour(sivas);
        erzincan.addNeighbour(malatya);
        erzincan.addDistance(267);
        erzincan.addDistance(131);
        erzincan.addDistance(275);
        erzincan.addDistance(190);
        erzincan.addDistance(155);
        erzincan.addDistance(133);
        erzincan.addDistance(295);
        erzincan.addDistance(248);
        erzincan.addDistance(363);

        erzurum.addNeighbour(bingöl);
        erzurum.addNeighbour(mus);
        erzurum.addNeighbour(agri);
        erzurum.addNeighbour(kars);
        erzurum.addNeighbour(ardahan);
        erzurum.addNeighbour(artvin);
        erzurum.addNeighbour(rize);
        erzurum.addNeighbour(bayburt);
        erzurum.addNeighbour(erzincan);
        erzurum.addDistance(177);
        erzurum.addDistance(266);
        erzurum.addDistance(183);
        erzurum.addDistance(203);
        erzurum.addDistance(233);
        erzurum.addDistance(226);
        erzurum.addDistance(259);
        erzurum.addDistance(125);
        erzurum.addDistance(190);

        eskisehir.addNeighbour(afyonkarahisar);
        eskisehir.addNeighbour(konya);
        eskisehir.addNeighbour(ankara);
        eskisehir.addNeighbour(bolu);
        eskisehir.addNeighbour(bilecik);
        eskisehir.addNeighbour(kutahya);
        eskisehir.addDistance(144);
        eskisehir.addDistance(338);
        eskisehir.addDistance(233);
        eskisehir.addDistance(291);
        eskisehir.addDistance(83);
        eskisehir.addDistance(78);

        gaziantep.addNeighbour(kilis);
        gaziantep.addNeighbour(sanliurfa);
        gaziantep.addNeighbour(adiyaman);
        gaziantep.addNeighbour(kahramanmaras);
        gaziantep.addNeighbour(osmaniye);
        gaziantep.addNeighbour(hatay);
        gaziantep.addDistance(64);
        gaziantep.addDistance(137);
        gaziantep.addDistance(150);
        gaziantep.addDistance(76);
        gaziantep.addDistance(125);
        gaziantep.addDistance(193);

        giresun.addNeighbour(gumushane);
        giresun.addNeighbour(trabzon);
        giresun.addNeighbour(erzincan);
        giresun.addNeighbour(sivas);
        giresun.addNeighbour(ordu);
        giresun.addDistance(162);
        giresun.addDistance(136);
        giresun.addDistance(295);
        giresun.addDistance(298);
        giresun.addDistance(44);

        gumushane.addNeighbour(erzincan);
        gumushane.addNeighbour(bayburt);
        gumushane.addNeighbour(trabzon);
        gumushane.addNeighbour(giresun);
        gumushane.addDistance(133);
        gumushane.addDistance(78);
        gumushane.addDistance(100);
        gumushane.addDistance(162);

        hakkari.addNeighbour(van);
        hakkari.addNeighbour(sirnak);
        hakkari.addDistance(197);
        hakkari.addDistance(189);

        hatay.addNeighbour(gaziantep);
        hatay.addNeighbour(osmaniye);
        hatay.addNeighbour(adana);
        hatay.addDistance(193);
        hatay.addDistance(129);
        hatay.addDistance(191);

        isparta.addNeighbour(antalya);
        isparta.addNeighbour(konya);
        isparta.addNeighbour(afyonkarahisar);
        isparta.addNeighbour(burdur);
        isparta.addDistance(130);
        isparta.addDistance(263);
        isparta.addDistance(168);
        isparta.addDistance(51);

        mersin.addNeighbour(adana);
        mersin.addNeighbour(nigde);
        mersin.addNeighbour(konya);
        mersin.addNeighbour(karaman);
        mersin.addNeighbour(antalya);
        mersin.addDistance(69);
        mersin.addDistance(200);
        mersin.addDistance(348);
        mersin.addDistance(235);
        mersin.addDistance(466);

        istanbul.addNeighbour(kocaeli);
        istanbul.addNeighbour(tekirdag);
        istanbul.addDistance(111);
        istanbul.addDistance(131);

        izmir.addNeighbour(aydin);
        izmir.addNeighbour(manisa);
        izmir.addNeighbour(balikesir);
        izmir.addDistance(126);
        izmir.addDistance(35);
        izmir.addDistance(176);

        kars.addNeighbour(agri);
        kars.addNeighbour(igdir);
        kars.addNeighbour(ardahan);
        kars.addNeighbour(erzurum);
        kars.addDistance(214);
        kars.addDistance(140);
        kars.addDistance(94);
        kars.addDistance(203);

        kastamonu.addNeighbour(corum);
        kastamonu.addNeighbour(sinop);
        kastamonu.addNeighbour(cankiri);
        kastamonu.addNeighbour(bartin);
        kastamonu.addNeighbour(karabuk);
        kastamonu.addDistance(197);
        kastamonu.addDistance(183);
        kastamonu.addDistance(106);
        kastamonu.addDistance(183);
        kastamonu.addDistance(114);

        kayseri.addNeighbour(adana);
        kayseri.addNeighbour(kahramanmaras);
        kayseri.addNeighbour(sivas);
        kayseri.addNeighbour(yozgat);
        kayseri.addNeighbour(nevsehir);
        kayseri.addNeighbour(nigde);
        kayseri.addDistance(335);
        kayseri.addDistance(261);
        kayseri.addDistance(194);
        kayseri.addDistance(197);
        kayseri.addDistance(81);
        kayseri.addDistance(128);

        kirklareli.addNeighbour(edirne);
        kirklareli.addNeighbour(tekirdag);
        kirklareli.addDistance(62);
        kirklareli.addDistance(121);

        kirsehir.addNeighbour(nevsehir);
        kirsehir.addNeighbour(yozgat);
        kirsehir.addNeighbour(kirikkale);
        kirsehir.addNeighbour(ankara);
        kirsehir.addNeighbour(aksaray);
        kirsehir.addDistance(91);
        kirsehir.addDistance(112);
        kirsehir.addDistance(113);
        kirsehir.addDistance(184);
        kirsehir.addDistance(110);

        kocaeli.addNeighbour(yalova);
        kocaeli.addNeighbour(istanbul);
        kocaeli.addNeighbour(bursa);
        kocaeli.addNeighbour(sakarya);
        kocaeli.addDistance(65);
        kocaeli.addDistance(111);
        kocaeli.addDistance(132);
        kocaeli.addDistance(37);

        konya.addNeighbour(antalya);
        konya.addNeighbour(karaman);
        konya.addNeighbour(mersin);
        konya.addNeighbour(nigde);
        konya.addNeighbour(aksaray);
        konya.addNeighbour(ankara);
        konya.addNeighbour(eskisehir);
        konya.addNeighbour(afyonkarahisar);
        konya.addNeighbour(isparta);
        konya.addDistance(322);
        konya.addDistance(119);
        konya.addDistance(348);
        konya.addDistance(242);
        konya.addDistance(148);
        konya.addDistance(258);
        konya.addDistance(338);
        konya.addDistance(223);
        konya.addDistance(263);

        kutahya.addNeighbour(manisa);
        kutahya.addNeighbour(usak);
        kutahya.addNeighbour(afyonkarahisar);
        kutahya.addNeighbour(eskisehir);
        kutahya.addNeighbour(bilecik);
        kutahya.addNeighbour(bursa);
        kutahya.addNeighbour(balikesir);
        kutahya.addDistance(316);
        kutahya.addDistance(139);
        kutahya.addDistance(100);
        kutahya.addDistance(78);
        kutahya.addDistance(112);
        kutahya.addDistance(177);
        kutahya.addDistance(228);

        malatya.addNeighbour(kahramanmaras);
        malatya.addNeighbour(adiyaman);
        malatya.addNeighbour(diyarbakir);
        malatya.addNeighbour(elazig);
        malatya.addNeighbour(erzincan);
        malatya.addNeighbour(sivas);
        malatya.addDistance(224);
        malatya.addDistance(187);
        malatya.addDistance(249);
        malatya.addDistance(98);
        malatya.addDistance(363);
        malatya.addDistance(243);

        manisa.addNeighbour(izmir);
        manisa.addNeighbour(aydin);
        manisa.addNeighbour(denizli);
        manisa.addNeighbour(usak);
        manisa.addNeighbour(kutahya);
        manisa.addNeighbour(balikesir);
        manisa.addDistance(35);
        manisa.addDistance(155);
        manisa.addDistance(208);
        manisa.addDistance(195);
        manisa.addDistance(316);
        manisa.addDistance(141);

        kahramanmaras.addNeighbour(gaziantep);
        kahramanmaras.addNeighbour(adiyaman);
        kahramanmaras.addNeighbour(malatya);
        kahramanmaras.addNeighbour(sivas);
        kahramanmaras.addNeighbour(kayseri);
        kahramanmaras.addNeighbour(adana);
        kahramanmaras.addNeighbour(osmaniye);
        kahramanmaras.addDistance(76);
        kahramanmaras.addDistance(163);
        kahramanmaras.addDistance(224);
        kahramanmaras.addDistance(327);
        kahramanmaras.addDistance(261);
        kahramanmaras.addDistance(192);
        kahramanmaras.addDistance(105);

        mardin.addNeighbour(sanliurfa);
        mardin.addNeighbour(diyarbakir);
        mardin.addNeighbour(batman);
        mardin.addNeighbour(siirt);
        mardin.addNeighbour(sirnak);
        mardin.addDistance(188);
        mardin.addDistance(96);
        mardin.addDistance(150);
        mardin.addDistance(227);
        mardin.addDistance(197);

        mugla.addNeighbour(antalya);
        mugla.addNeighbour(burdur);
        mugla.addNeighbour(denizli);
        mugla.addNeighbour(aydin);
        mugla.addDistance(311);
        mugla.addDistance(241);
        mugla.addDistance(145);
        mugla.addDistance(99);

        mus.addNeighbour(diyarbakir);
        mus.addNeighbour(batman);
        mus.addNeighbour(bitlis);
        mus.addNeighbour(agri);
        mus.addNeighbour(erzurum);
        mus.addNeighbour(bingöl);
        mus.addDistance(252);
        mus.addDistance(218);
        mus.addDistance(83);
        mus.addDistance(245);
        mus.addDistance(266);
        mus.addDistance(111);

        nevsehir.addNeighbour(nigde);
        nevsehir.addNeighbour(kayseri);
        nevsehir.addNeighbour(yozgat);
        nevsehir.addNeighbour(kirsehir);
        nevsehir.addNeighbour(aksaray);
        nevsehir.addDistance(82);
        nevsehir.addDistance(81);
        nevsehir.addDistance(203);
        nevsehir.addDistance(91);
        nevsehir.addDistance(75);

        nigde.addNeighbour(nevsehir);
        nigde.addNeighbour(kayseri);
        nigde.addNeighbour(adana);
        nigde.addNeighbour(mersin);
        nigde.addNeighbour(konya);
        nigde.addNeighbour(aksaray);
        nigde.addDistance(82);
        nigde.addDistance(128);
        nigde.addDistance(207);
        nigde.addDistance(200);
        nigde.addDistance(242);
        nigde.addDistance(122);

        ordu.addNeighbour(samsun);
        ordu.addNeighbour(tokat);
        ordu.addNeighbour(giresun);
        ordu.addNeighbour(sivas);
        ordu.addDistance(150);
        ordu.addDistance(216);
        ordu.addDistance(44);
        ordu.addDistance(314);

        rize.addNeighbour(artvin);
        rize.addNeighbour(erzurum);
        rize.addNeighbour(bayburt);
        rize.addNeighbour(trabzon);
        rize.addDistance(161);
        rize.addDistance(259);
        rize.addDistance(253);
        rize.addDistance(75);

        sakarya.addNeighbour(duzce);
        sakarya.addNeighbour(bolu);
        sakarya.addNeighbour(bilecik);
        sakarya.addNeighbour(bursa);
        sakarya.addNeighbour(kocaeli);
        sakarya.addDistance(69);
        sakarya.addDistance(114);
        sakarya.addDistance(99);
        sakarya.addDistance(157);
        sakarya.addDistance(37);

        samsun.addNeighbour(ordu);
        samsun.addNeighbour(tokat);
        samsun.addNeighbour(amasya);
        samsun.addNeighbour(corum);
        samsun.addNeighbour(sinop);
        samsun.addDistance(150);
        samsun.addDistance(229);
        samsun.addDistance(131);
        samsun.addDistance(172);
        samsun.addDistance(155);

        siirt.addNeighbour(van);
        siirt.addNeighbour(bitlis);
        siirt.addNeighbour(batman);
        siirt.addNeighbour(mardin);
        siirt.addNeighbour(sirnak);
        siirt.addDistance(257);
        siirt.addDistance(96);
        siirt.addDistance(86);
        siirt.addDistance(227);
        siirt.addDistance(100);

        sinop.addNeighbour(samsun);
        sinop.addNeighbour(corum);
        sinop.addNeighbour(kastamonu);
        sinop.addDistance(155);
        sinop.addDistance(266);
        sinop.addDistance(183);

        sivas.addNeighbour(kayseri);
        sivas.addNeighbour(kahramanmaras);
        sivas.addNeighbour(malatya);
        sivas.addNeighbour(erzincan);
        sivas.addNeighbour(giresun);
        sivas.addNeighbour(ordu);
        sivas.addNeighbour(tokat);
        sivas.addNeighbour(yozgat);
        sivas.addDistance(194);
        sivas.addDistance(327);
        sivas.addDistance(243);
        sivas.addDistance(248);
        sivas.addDistance(298);
        sivas.addDistance(314);
        sivas.addDistance(108);
        sivas.addDistance(224);

        tekirdag.addNeighbour(istanbul);
        tekirdag.addNeighbour(kirklareli);
        tekirdag.addNeighbour(edirne);
        tekirdag.addNeighbour(canakkale);
        tekirdag.addDistance(131);
        tekirdag.addDistance(121);
        tekirdag.addDistance(140);
        tekirdag.addDistance(187);

        tokat.addNeighbour(sivas);
        tokat.addNeighbour(ordu);
        tokat.addNeighbour(samsun);
        tokat.addNeighbour(amasya);
        tokat.addNeighbour(yozgat);
        tokat.addDistance(108);
        tokat.addDistance(216);
        tokat.addDistance(229);
        tokat.addDistance(114);
        tokat.addDistance(205);

        trabzon.addNeighbour(rize);
        trabzon.addNeighbour(bayburt);
        trabzon.addNeighbour(gumushane);
        trabzon.addNeighbour(giresun);
        trabzon.addDistance(75);
        trabzon.addDistance(178);
        trabzon.addDistance(100);
        trabzon.addDistance(136);

        tunceli.addNeighbour(elazig);
        tunceli.addNeighbour(bingöl);
        tunceli.addNeighbour(erzincan);
        tunceli.addDistance(136);
        tunceli.addDistance(144);
        tunceli.addDistance(131);

        sanliurfa.addNeighbour(gaziantep);
        sanliurfa.addNeighbour(adiyaman);
        sanliurfa.addNeighbour(diyarbakir);
        sanliurfa.addNeighbour(mardin);
        sanliurfa.addDistance(137);
        sanliurfa.addDistance(112);
        sanliurfa.addDistance(176);
        sanliurfa.addDistance(188);

        usak.addNeighbour(manisa);
        usak.addNeighbour(denizli);
        usak.addNeighbour(afyonkarahisar);
        usak.addNeighbour(kutahya);
        usak.addDistance(195);
        usak.addDistance(150);
        usak.addDistance(115);
        usak.addDistance(139);

        van.addNeighbour(hakkari);
        van.addNeighbour(sirnak);
        van.addNeighbour(siirt);
        van.addNeighbour(bitlis);
        van.addNeighbour(agri);
        van.addDistance(197);
        van.addDistance(357);
        van.addDistance(257);
        van.addDistance(161);
        van.addDistance(228);

        yozgat.addNeighbour(kayseri);
        yozgat.addNeighbour(sivas);
        yozgat.addNeighbour(tokat);
        yozgat.addNeighbour(amasya);
        yozgat.addNeighbour(corum);
        yozgat.addNeighbour(kirikkale);
        yozgat.addNeighbour(kirsehir);
        yozgat.addNeighbour(nevsehir);
        yozgat.addDistance(197);
        yozgat.addDistance(224);
        yozgat.addDistance(205);
        yozgat.addDistance(200);
        yozgat.addDistance(108);
        yozgat.addDistance(140);
        yozgat.addDistance(112);
        yozgat.addDistance(203);

        zonguldak.addNeighbour(bartin);
        zonguldak.addNeighbour(bolu);
        zonguldak.addNeighbour(duzce);
        zonguldak.addNeighbour(karabuk);
        zonguldak.addDistance(87);
        zonguldak.addDistance(157);
        zonguldak.addDistance(113);
        zonguldak.addDistance(100);

        aksaray.addNeighbour(nigde);
        aksaray.addNeighbour(nevsehir);
        aksaray.addNeighbour(kirsehir);
        aksaray.addNeighbour(ankara);
        aksaray.addNeighbour(konya);
        aksaray.addDistance(122);
        aksaray.addDistance(75);
        aksaray.addDistance(110);
        aksaray.addDistance(225);
        aksaray.addDistance(148);

        bayburt.addNeighbour(erzincan);
        bayburt.addNeighbour(erzurum);
        bayburt.addNeighbour(rize);
        bayburt.addNeighbour(trabzon);
        bayburt.addNeighbour(gumushane);
        bayburt.addDistance(155);
        bayburt.addDistance(125);
        bayburt.addDistance(253);
        bayburt.addDistance(178);
        bayburt.addDistance(78);

        karaman.addNeighbour(mersin);
        karaman.addNeighbour(konya);
        karaman.addNeighbour(antalya);
        karaman.addDistance(235);
        karaman.addDistance(119);
        karaman.addDistance(374);

        kirikkale.addNeighbour(kirsehir);
        kirikkale.addNeighbour(yozgat);
        kirikkale.addNeighbour(corum);
        kirikkale.addNeighbour(cankiri);
        kirikkale.addNeighbour(ankara);
        kirikkale.addDistance(113);
        kirikkale.addDistance(140);
        kirikkale.addDistance(166);
        kirikkale.addDistance(104);
        kirikkale.addDistance(75);

        batman.addNeighbour(mardin);
        batman.addNeighbour(siirt);
        batman.addNeighbour(bitlis);
        batman.addNeighbour(mus);
        batman.addNeighbour(diyarbakir);
        batman.addDistance(150);
        batman.addDistance(86);
        batman.addDistance(135);
        batman.addDistance(218);
        batman.addDistance(100);

        sirnak.addNeighbour(mardin);
        sirnak.addNeighbour(siirt);
        sirnak.addNeighbour(van);
        sirnak.addNeighbour(hakkari);
        sirnak.addDistance(197);
        sirnak.addDistance(100);
        sirnak.addDistance(357);
        sirnak.addDistance(189);

        bartin.addNeighbour(kastamonu);
        bartin.addNeighbour(zonguldak);
        bartin.addNeighbour(karabuk);
        bartin.addDistance(183);
        bartin.addDistance(87);
        bartin.addDistance(89);

        ardahan.addNeighbour(kars);
        ardahan.addNeighbour(erzurum);
        ardahan.addNeighbour(artvin);
        ardahan.addDistance(94);
        ardahan.addDistance(233);
        ardahan.addDistance(116);

        igdir.addNeighbour(agri);
        igdir.addNeighbour(kars);
        igdir.addDistance(143);
        igdir.addDistance(140);

        yalova.addNeighbour(kocaeli);
        yalova.addNeighbour(bursa);
        yalova.addDistance(65);
        yalova.addDistance(69);

        karabuk.addNeighbour(zonguldak);
        karabuk.addNeighbour(bartin);
        karabuk.addNeighbour(kastamonu);
        karabuk.addNeighbour(cankiri);
        karabuk.addNeighbour(bolu);
        karabuk.addDistance(100);
        karabuk.addDistance(89);
        karabuk.addDistance(114);
        karabuk.addDistance(193);
        karabuk.addDistance(134);

        kilis.addNeighbour(gaziantep);
        kilis.addDistance(64);

        osmaniye.addNeighbour(gaziantep);
        osmaniye.addNeighbour(kahramanmaras);
        osmaniye.addNeighbour(adana);
        osmaniye.addNeighbour(hatay);
        osmaniye.addDistance(125);
        osmaniye.addDistance(105);
        osmaniye.addDistance(87);
        osmaniye.addDistance(129);

        duzce.addNeighbour(zonguldak);
        duzce.addNeighbour(bolu);
        duzce.addNeighbour(sakarya);
        duzce.addDistance(113);
        duzce.addDistance(45);
        duzce.addDistance(69);

        Graph graph = new Graph();

        graph.createGraph(adana);
        graph.createGraph(adiyaman);
        graph.createGraph(afyonkarahisar);
        graph.createGraph(agri);
        graph.createGraph(amasya);
        graph.createGraph(ankara);
        graph.createGraph(antalya);
        graph.createGraph(artvin);
        graph.createGraph(aydin);
        graph.createGraph(balikesir);
        graph.createGraph(bilecik);
        graph.createGraph(bingöl);
        graph.createGraph(bitlis);
        graph.createGraph(bolu);
        graph.createGraph(burdur);
        graph.createGraph(bursa);
        graph.createGraph(canakkale);
        graph.createGraph(cankiri);
        graph.createGraph(corum);
        graph.createGraph(denizli);
        graph.createGraph(diyarbakir);
        graph.createGraph(edirne);
        graph.createGraph(elazig);
        graph.createGraph(erzincan);
        graph.createGraph(erzurum);
        graph.createGraph(eskisehir);
        graph.createGraph(gaziantep);
        graph.createGraph(giresun);
        graph.createGraph(gumushane);
        graph.createGraph(hakkari);
        graph.createGraph(hatay);
        graph.createGraph(isparta);
        graph.createGraph(mersin);
        graph.createGraph(istanbul);
        graph.createGraph(izmir);
        graph.createGraph(kars);
        graph.createGraph(kastamonu);
        graph.createGraph(kayseri);
        graph.createGraph(kirklareli);
        graph.createGraph(kirsehir);
        graph.createGraph(kocaeli);
        graph.createGraph(konya);
        graph.createGraph(kutahya);
        graph.createGraph(malatya);
        graph.createGraph(manisa);
        graph.createGraph(kahramanmaras);
        graph.createGraph(mardin);
        graph.createGraph(mugla);
        graph.createGraph(mus);
        graph.createGraph(nevsehir);
        graph.createGraph(nigde);
        graph.createGraph(ordu);
        graph.createGraph(rize);
        graph.createGraph(sakarya);
        graph.createGraph(samsun);
        graph.createGraph(siirt);
        graph.createGraph(sinop);
        graph.createGraph(sivas);
        graph.createGraph(tekirdag);
        graph.createGraph(tokat);
        graph.createGraph(trabzon);
        graph.createGraph(tunceli);
        graph.createGraph(sanliurfa);
        graph.createGraph(usak);
        graph.createGraph(van);
        graph.createGraph(yozgat);
        graph.createGraph(zonguldak);
        graph.createGraph(aksaray);
        graph.createGraph(bayburt);
        graph.createGraph(karaman);
        graph.createGraph(kirikkale);
        graph.createGraph(batman);
        graph.createGraph(sirnak);
        graph.createGraph(bartin);
        graph.createGraph(ardahan);
        graph.createGraph(igdir);
        graph.createGraph(yalova);
        graph.createGraph(karabuk);
        graph.createGraph(kilis);
        graph.createGraph(osmaniye);
        graph.createGraph(duzce);

        int icontrol = 0;
        int tcontrol = 0;
        int econtrol = 0;
        int kcontrol = 0;
        int isfinish = 0;
        ArrayList<String> way = new ArrayList<String>();
        ArrayList<Integer> price = new ArrayList<Integer>();
        ArrayList<Node> lastNode = new ArrayList<Node>();
        way.add("Kocaeli");

        if (choose_set.contains("Tekirdağ") || choose_set.contains("Kırklareli") || choose_set.contains("Edirne") || choose_set.contains("İstanbul")) {

            if (choose_set.contains("İstanbul")) {

                icontrol++;
                isfinish++;
                choose_set.remove("İstanbul");

            }

            if (choose_set.contains("Tekirdağ")) {

                tcontrol++;
                isfinish++;
                choose_set.remove("Tekirdağ");

            }
            if (choose_set.contains("Kırklareli")) {

                kcontrol++;
                isfinish++;
                choose_set.remove("Kırklareli");

            }
            if (choose_set.contains("Edirne")) {

                econtrol++;
                isfinish++;
                choose_set.remove("Edirne");

            }

            if (icontrol == 0 && tcontrol == 0 && kcontrol == 0 && econtrol == 1) {

                way.add("İstanbul");
                way.add("Tekirdağ");
                way.add("Edirne");
                price.add(111);
                price.add(131);
                price.add(140);
                way.add("Tekirdağ");
                way.add("İstanbul");
                way.add("Kocaeli");
                price.add(140);
                price.add(131);
                price.add(111);

            }
            if (icontrol == 0 && tcontrol == 0 && kcontrol == 1 && econtrol == 0) {

                way.add("İstanbul");
                way.add("Tekirdağ");
                way.add("Kırklareli");
                price.add(111);
                price.add(131);
                price.add(121);
                way.add("Tekirdağ");
                way.add("İstanbul");
                way.add("Kocaeli");
                price.add(121);
                price.add(131);
                price.add(111);

            }
            if (icontrol == 0 && tcontrol == 0 && kcontrol == 1 && econtrol == 1) {

                way.add("İstanbul");
                way.add("Tekirdağ");
                way.add("Kırklareli");
                way.add("Edirne");
                price.add(111);
                price.add(131);
                price.add(121);
                price.add(62);
                way.add("Tekirdağ");
                way.add("İstanbul");
                way.add("Kocaeli");
                price.add(140);
                price.add(131);
                price.add(111);

            }
            if (icontrol == 0 && tcontrol == 1 && kcontrol == 0 && econtrol == 0) {

                way.add("İstanbul");
                way.add("Tekirdağ");

                price.add(111);
                price.add(131);

                way.add("İstanbul");
                way.add("Kocaeli");

                price.add(131);
                price.add(111);

            }
            if (icontrol == 0 && tcontrol == 1 && kcontrol == 0 && econtrol == 1) {

                way.add("İstanbul");
                way.add("Tekirdağ");
                way.add("Edirne");
                price.add(111);
                price.add(131);
                price.add(140);
                way.add("Tekirdağ");
                way.add("İstanbul");
                way.add("Kocaeli");
                price.add(140);
                price.add(131);
                price.add(111);

            }
            if (icontrol == 0 && tcontrol == 1 && kcontrol == 1 && econtrol == 0) {

                way.add("İstanbul");
                way.add("Tekirdağ");
                way.add("Kırklareli");
                price.add(111);
                price.add(131);
                price.add(121);
                way.add("Tekirdağ");
                way.add("İstanbul");
                way.add("Kocaeli");
                price.add(121);
                price.add(131);
                price.add(111);

            }
            if (icontrol == 0 && tcontrol == 1 && kcontrol == 1 && econtrol == 1) {

                way.add("İstanbul");
                way.add("Tekirdağ");
                way.add("Kırklareli");
                way.add("Edirne");
                price.add(111);
                price.add(131);
                price.add(121);
                price.add(62);
                way.add("Tekirdağ");
                way.add("İstanbul");
                way.add("Kocaeli");
                price.add(140);
                price.add(131);
                price.add(111);

            }
            if (icontrol == 1 && tcontrol == 0 && kcontrol == 0 && econtrol == 0) {

                way.add("İstanbul");
                price.add(111);
                way.add("Kocaeli");
                price.add(111);

            }
            if (icontrol == 1 && tcontrol == 0 && kcontrol == 0 && econtrol == 1) {

                way.add("İstanbul");
                way.add("Tekirdağ");
                way.add("Edirne");
                price.add(111);
                price.add(131);
                price.add(140);
                way.add("Tekirdağ");
                way.add("İstanbul");
                way.add("Kocaeli");
                price.add(140);
                price.add(131);
                price.add(111);

            }
            if (icontrol == 1 && tcontrol == 0 && kcontrol == 1 && econtrol == 0) {

                way.add("İstanbul");
                way.add("Tekirdağ");
                way.add("Kırklareli");
                price.add(111);
                price.add(131);
                price.add(121);
                way.add("Tekirdağ");
                way.add("İstanbul");
                way.add("Kocaeli");
                price.add(121);
                price.add(131);
                price.add(111);

            }
            if (icontrol == 1 && tcontrol == 0 && kcontrol == 1 && econtrol == 1) {

                way.add("İstanbul");
                way.add("Tekirdağ");
                way.add("Kırklareli");
                way.add("Edirne");
                price.add(111);
                price.add(131);
                price.add(121);
                price.add(62);
                way.add("Tekirdağ");
                way.add("İstanbul");
                way.add("Kocaeli");
                price.add(140);
                price.add(131);
                price.add(111);

            }

            if (icontrol == 1 && tcontrol == 1 && kcontrol == 0 && econtrol == 0) {

                way.add("İstanbul");
                way.add("Tekirdağ");

                price.add(111);
                price.add(131);

                way.add("İstanbul");
                way.add("Kocaeli");

                price.add(131);
                price.add(111);

            }
            if (icontrol == 1 && tcontrol == 1 && kcontrol == 0 && econtrol == 1) {

                way.add("İstanbul");
                way.add("Tekirdağ");
                way.add("Edirne");
                price.add(111);
                price.add(131);
                price.add(140);
                way.add("Tekirdağ");
                way.add("İstanbul");
                way.add("Kocaeli");
                price.add(140);
                price.add(131);
                price.add(111);

            }
            if (icontrol == 1 && tcontrol == 1 && kcontrol == 1 && econtrol == 0) {

                way.add("İstanbul");
                way.add("Tekirdağ");
                way.add("Kırklareli");
                price.add(111);
                price.add(131);
                price.add(121);
                way.add("Tekirdağ");
                way.add("İstanbul");
                way.add("Kocaeli");
                price.add(121);
                price.add(131);
                price.add(111);

            }
            if (icontrol == 1 && tcontrol == 1 && kcontrol == 1 && econtrol == 1) {

                way.add("İstanbul");
                way.add("Tekirdağ");
                way.add("Kırklareli");
                way.add("Edirne");
                price.add(111);
                price.add(131);
                price.add(121);
                price.add(62);
                way.add("Tekirdağ");
                way.add("İstanbul");
                way.add("Kocaeli");
                price.add(140);
                price.add(131);
                price.add(111);

            }

        }
        
       

        lastNode.add(kocaeli);
        ArrayList<Node> memory = new ArrayList<Node>();
        ArrayList<String> way_temp = new ArrayList<String>();
        ArrayList<Integer> distance_temp = new ArrayList<Integer>();
        ArrayList<String> choose_set_temp = new ArrayList<String>();
        ArrayList<Node> lastNode_temp=new ArrayList<Node>();
        ArrayList<Node> adana_temp=new ArrayList<Node>();
        adana_temp=(ArrayList)adana.neighbour.clone();
        ArrayList<Node> urfa_temp=new ArrayList<Node>();
        ArrayList<Node> maras_temp=new ArrayList<Node>();
        urfa_temp=(ArrayList)sanliurfa.neighbour.clone();
        maras_temp=(ArrayList)kahramanmaras.neighbour.clone();
        lastNode_temp.add(kocaeli);
        way_temp = (ArrayList) way.clone();
        distance_temp = (ArrayList) price.clone();
        choose_set_temp = (ArrayList) choose_set.clone();
        ArrayList<Integer> total_price=new ArrayList<Integer>();
        String[][] file_memory = new String[1000][1000];
        
        int way_loop=0;
        int total=0;
        int rand_control=0;
        
        int random = 0;
        int new_loop = 0;
        int n_random = 0;
        int loop = 0;
        int size_control = way.size();
        int bug_fix=0;
         if(choose_set.contains("İstanbul")){
            
            choose_set.remove("İstanbul");
        }
        if(choose_set.contains("Tekirdağ")){
            
            choose_set.remove("Tekirdağ");
        }
        
        if(choose_set.contains("Kırklareli")){
            
            choose_set.remove("Kırklareli");
        }
        if(choose_set.contains("Edirne")){
            
            choose_set.remove("Edirne");
        }
        
        while (true) {
                if(way_loop==10){
                    break;
                    
                }
            for (int i = loop; i < lastNode.size(); i++) {
                    
                    if(random>=lastNode.get(0).neighbour.size()){
                        
                        random =(int)(Math.random()*lastNode.get(0).neighbour.size());
                    }
                    
                    System.out.println(lastNode.get(0).city_name);
                    System.out.println(lastNode.get(0).neighbour.size());
                   if(lastNode.get(i).equals(adana)){
                       
                       if(lastNode.get(i).neighbour.size()>6)
                           bug_fix++;
                           
                       
                   }
                   if(bug_fix==1){
                       lastNode.get(0).neighbour.clear();
                       lastNode.get(0).neighbour=(ArrayList)adana_temp.clone();       
                       bug_fix=0;
                       
                       random=(int)(Math.random()*6);
                   }
                   
                   random=(int)(Math.random()*lastNode.get(0).neighbour.size());
                   System.out.println(random);
                   if(random>lastNode.get(0).neighbour.size()){
                       random=(int)(Math.random()*lastNode.get(0).neighbour.size());
                       System.out.println(random);
                       
                   }
                   if(lastNode.get(i).equals(adana)){
                       
                       if(lastNode.get(i).neighbour.size()>6)
                           bug_fix++;
                           
                       
                   }
                   if(bug_fix==1){
                       lastNode.get(0).neighbour.clear();
                       lastNode.get(0).neighbour=(ArrayList)adana_temp.clone();       
                       bug_fix=0;
                       
                       random=(int)(Math.random()*6);
                   }
                   if(lastNode.get(0).equals(adana)){
                       random=(int)(Math.random()*6);
                       if(random==2){
                           random=1;
                           
                       }
                       lastNode.add(adana_temp.get(random));
                       lastNode.remove(0);
                       
                       
                   }
                   if(lastNode.get(0).equals(sanliurfa)){
                       
                       random=(int)(Math.random()*4);
                       lastNode.add(urfa_temp.get(random));
                       lastNode.remove(0);
                       
                   }
                   if(lastNode.get(0).equals(kahramanmaras)){
                       
                       random=(int)(Math.random()*7);
                       if(random==5){
                           random=4;
                       }
                       lastNode.add(maras_temp.get(random));
                       lastNode.remove(0);
                   }
                   System.out.println(lastNode.get(0).neighbour.size()+" "+lastNode.get(0).city_name);
                for (int j = 0; j < lastNode.get(i).neighbour.size(); j++) {
                    for (int k = 0; k < choose_set.size(); k++) {
                        if (lastNode.get(i).neighbour.get(j).city_name.equals(choose_set.get(k))) {

                            way.add(lastNode.get(i).neighbour.get(j).city_name);
                            price.add(lastNode.get(i).distance.get(j));
                            lastNode.add(lastNode.get(i).neighbour.get(j));
                            choose_set.remove(k);
                            //memory.add(lastNode.get(i).neighbour.get(j));

                        }
                    }

                }
                
                
                //memory.add(lastNode.get(0));
                //System.out.println(lastNode.get(i).city_name);
                //System.out.println(random);
               
                if(random>=lastNode.get(0).neighbour.size()){
                        
                        random =(int)(Math.random()*lastNode.get(0).neighbour.size());
                    }
                if(lastNode.get(0).neighbour.size() == 1){
                    new_loop++;
                    
                }
                   
                if (choose_set.isEmpty()) {
                    
                    for(int a=0;a<price.size();a++){
                        
                        total=price.get(a)+total;
                        
                        
                    }
                    
                   for(int a=0;a<way.size();a++){
                       
                       file_memory[way_loop][a]=way.get(a);
                       
                   } 
                    
                    total_price.add(total);
                    total=0;
                    price.clear();
                    way.clear();
                    lastNode.remove(0);
                    way_loop++;
                    way.add("Kocaeli");
                    
                    
                    random = (int)(Math.random()*lastNode.get(0).neighbour.size());
                    
                    
                    
                    lastNode=(ArrayList)lastNode_temp.clone();
                    
                    choose_set=(ArrayList)choose_set_temp.clone();
                    if(way_loop==10){
                        
                        break;
                        
                        
                    }
                    
                  
                    //break;

                } 
                
                else {

                    if (lastNode.size() == 2) {
                        
                        lastNode.remove(0);
                        
                    } else {
                           
                        if (memory.contains(lastNode.get(0).neighbour.get(random))) {
                            if (lastNode.get(0).neighbour.size() == 1) {

                                new_loop++;
                                

                            } else {
                                random = (int)(Math.random()*lastNode.get(0).neighbour.size());
                                
                                

                            }

                        } else {
                            
                            if(random>=lastNode.get(0).neighbour.size()){
                        
                           random =(int)(Math.random()*lastNode.get(0).neighbour.size());
                           }
                            if(way.contains(lastNode.get(0).neighbour.get(random).city_name)){
                                
                                for(int w=0;w<lastNode.get(0).neighbour.size();w++){
                                        
                                    if(way.contains(lastNode.get(0).neighbour.get(w).city_name)){
                                         rand_control++;
                                        
                                    
                                }else{
                                        random=w;
                                        break;
                                    }
                            }
                            }
                            /*if(rand_control==lastNode.get(0).neighbour.size()){
                                
                                  // new_loop++;
                            }*/
                            rand_control=0;
                            lastNode.add(lastNode.get(0).neighbour.get(random));
                           // memory.add(lastNode.get(0).neighbour.get(random));
                            way.add(lastNode.get(0).neighbour.get(random).city_name);
                            price.add(lastNode.get(0).distance.get(random));
                            //System.out.println(lastNode.get(0).neighbour.get(random).city_name+"eklendi");
                            lastNode.remove(0);
                            
                            random =(int)(Math.random()*lastNode.get(0).neighbour.size());
                            if(random>=lastNode.get(0).neighbour.size()){
                        
                           random =(int)(Math.random()*lastNode.get(0).neighbour.size());
                           }
                          

                        }

                    }

                }
               // System.out.println(random);
                //System.out.println(lastNode.get(0).neighbour.size());
                if (random >= lastNode.get(0).neighbour.size()) {

                    //new_loop++;
                    random = (int)(Math.random()*lastNode.get(0).neighbour.size());

                }

            }
            if (new_loop == 1) {

                lastNode.clear();
                lastNode.add(kocaeli);
                /*memory.remove(bursa);
                memory.remove(yalova);
                memory.remove(sakarya);*/
                choose_set.clear();
                choose_set = (ArrayList) choose_set_temp.clone();
                n_random++;
                loop = 0;
                random = (int)(Math.random()*lastNode.get(0).neighbour.size());
                
                new_loop = 0;
                way.clear();
                price.clear();
                way = (ArrayList) way_temp.clone();
                price = (ArrayList) distance_temp.clone();
                if (random >= lastNode.get(0).neighbour.size()) {

                    //new_loop++;
                    random = (int)(Math.random()*lastNode.get(0).neighbour.size());

                }

            }

            if (choose_set.isEmpty()) {
                
                for(int b=0;b<price.size();b++){
                        
                        total=price.get(b)+total;
                        
                        
                    }
                    total_price.add(total);
                    price.clear();
                    way.clear();
                    lastNode.clear();
                    way_loop++;
                    random = (int)(Math.random()*lastNode.get(0).neighbour.size());
                    lastNode.add(kocaeli);
                    choose_set=(ArrayList)choose_set_temp.clone();
                    if(way_loop==10){
                        
                        break;
                    }
                    if (random >= lastNode.get(0).neighbour.size()) {

                    //new_loop++;
                    random = (int)(Math.random()*lastNode.get(0).neighbour.size());

                }

                //break;

            }

        }
       
        
            FileWriter fw;
        try {
            fw = new FileWriter("‪proje.txt");
            PrintWriter pw=new PrintWriter(fw);
         for (int i=0;i<10;i++){
             pw.print((i+1)+".Güzergah:)");
         for(int j=0;j<1000;j++){
             if(file_memory[i][j]==null){
                 continue;
             }else
              pw.print(file_memory[i][j]+" ");    
             System.out.print(file_memory[i][j]+" ");
             
         }       
        pw.println();
        pw.print((i+1)+".Güzergahın Maliyeti:"+total_price.get(i)*2);
        pw.println();
        System.out.println("\n");
    }
       
       for(int i=0;i<total_price.size();i++){
           
           System.out.println(total_price.get(i));
           
       }
            pw.close();
            
        } catch (IOException ex) {
            System.out.println("Dosya Açılamadı");
        }
            
        
       for (int i=0;i<10;i++){
         for(int j=0;j<1000;j++){
             if(file_memory[i][j]==null){
                 continue;
             }else
             System.out.print(file_memory[i][j]+" ");
             
         }        
        System.out.println("\n");
    }
       
       for(int i=0;i<total_price.size();i++){
           
           System.out.println(total_price.get(i));
           
       }

      System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adana;
    private javax.swing.JCheckBox adiyaman;
    private javax.swing.JCheckBox afyonkarahisar;
    private javax.swing.JCheckBox agri;
    private javax.swing.JCheckBox aksaray;
    private javax.swing.JCheckBox amasya;
    private javax.swing.JCheckBox ankara;
    private javax.swing.JCheckBox antalya;
    private javax.swing.JCheckBox ardahan;
    private javax.swing.JCheckBox artvin;
    private javax.swing.JCheckBox aydin;
    private javax.swing.JCheckBox balikesir;
    private javax.swing.JCheckBox bartin;
    private javax.swing.JCheckBox batman;
    private javax.swing.JCheckBox bayburt;
    private javax.swing.JCheckBox bilecik;
    private javax.swing.JCheckBox bingöl;
    private javax.swing.JCheckBox bitlis;
    private javax.swing.JCheckBox bolu;
    private javax.swing.JCheckBox burdur;
    private javax.swing.JCheckBox bursa;
    private javax.swing.JCheckBox canakkale;
    private javax.swing.JCheckBox cankiri;
    private javax.swing.JCheckBox corum;
    private javax.swing.JCheckBox denizli;
    private javax.swing.JCheckBox diyarbakir;
    private javax.swing.JCheckBox duzce;
    private javax.swing.JCheckBox edirne;
    private javax.swing.JCheckBox elazig;
    private javax.swing.JCheckBox erzincan;
    private javax.swing.JCheckBox erzurum;
    private javax.swing.JCheckBox eskisehir;
    private javax.swing.JCheckBox gaziantep;
    private javax.swing.JCheckBox giresun;
    private javax.swing.JCheckBox gumushane;
    private javax.swing.JCheckBox hakkari;
    private javax.swing.JCheckBox hatay;
    private javax.swing.JCheckBox igdir;
    private javax.swing.JCheckBox isparta;
    private javax.swing.JCheckBox istanbul;
    private javax.swing.JCheckBox izmir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox kahramanmaras;
    private javax.swing.JCheckBox karabuk;
    private javax.swing.JCheckBox karaman;
    private javax.swing.JCheckBox kars;
    private javax.swing.JCheckBox kastamonu;
    private javax.swing.JCheckBox kayseri;
    private javax.swing.JCheckBox kilis;
    private javax.swing.JCheckBox kirikkale;
    private javax.swing.JCheckBox kirklareli;
    private javax.swing.JCheckBox kirsehir;
    private javax.swing.JCheckBox konya;
    private javax.swing.JCheckBox kutahya;
    private javax.swing.JCheckBox malatya;
    private javax.swing.JCheckBox manisa;
    private javax.swing.JCheckBox mardin;
    private javax.swing.JCheckBox mersin;
    private javax.swing.JCheckBox mugla;
    private javax.swing.JCheckBox mus;
    private javax.swing.JCheckBox nevsehir;
    private javax.swing.JCheckBox nigde;
    private javax.swing.JCheckBox ordu;
    private javax.swing.JCheckBox osmaniye;
    private javax.swing.JCheckBox rize;
    private javax.swing.JCheckBox sakarya;
    private javax.swing.JCheckBox samsun;
    private javax.swing.JCheckBox sanliurfa;
    private javax.swing.JCheckBox siirt;
    private javax.swing.JCheckBox sinop;
    private javax.swing.JCheckBox sirnak;
    private javax.swing.JCheckBox sivas;
    private javax.swing.JCheckBox tekirdag;
    private javax.swing.JCheckBox tokat;
    private javax.swing.JCheckBox trabzon;
    private javax.swing.JCheckBox tunceli;
    private javax.swing.JCheckBox usak;
    private javax.swing.JCheckBox van;
    private javax.swing.JCheckBox yalova;
    private javax.swing.JCheckBox yozgat;
    private javax.swing.JCheckBox zonguldak;
    // End of variables declaration//GEN-END:variables
}
